sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-040
env:
  global:
    -
      # LTD_AWS_ID
      secure: fwY/P2lX0+LDqO+RvPz8qsizzLfnNwBMOXiK5VL2FD1VYFxaUYxNyBQsOOKAXD+j/rB3YmQfDlxi8s+AVgT24+0j0wFo3VJwOtWbKbg2NGgBZN5rcRsxLvRkiduPIYDNjO8YIQQilW+mfCHlbIpOqAbW9BSyNsXtm4yV59dvlR0o7kZtaA0AlJjMAhYcUp1/13B1JLq48X8FOPFRIQLIvr6f9WHVzUBP2g3DURHEtmmHYuayLQW4WOCk56RkjLcZeIJT0kcpigpbpQpztOZrslqlsxvak1sv43dyZ0et53IeXvqdaxRwM03I8HvJGZzORn/g2r7uFCIIv0447/VpyfvroaGQeoNJyeKo4VM9h8yFmAWxQ+rjyIxJat7dQxpEr/g1q9MFYhGPd12SFKXbVpheNkOGqGr1hZkjeyzTBSwz54mi9YdfPLb6pdf69n3J0UB57GrxJz+KysCsP54Nf9RfEDSlF1GJLyO8nKdYrqUjRDoiLJKSU0j0PEH+3cPJPzx5iGO1WjxnmTXURwpYAmV8zAoASjfa607vY66SHcTHIPe4itceyaQhL8TbYBXBgxsYrwEkywXh9wVpDNJ1LLHZFkP82YLkHkkwMcQW0FDT0OqpQOpFb+yH4bkFh49hFjWeyMYIB/q5HxXYrnsn4cpSJEbk8qWTIHueeRBsb1I=
    -
      # LTD_AWS_SECRET
      secure: PReqwkAj16kORqZHoo5JvLWm5dy9uCW4mCDkYL+1wcr94QRi0Soct2xag5pOWkmeySbTsNXtQSM2Gg5wYUyBOQ8dWKwG7/F5PJCJ+MncnboacuSWFWtaS6M7NL1Hn2nBU6OaTmW15TwCFxQ9I2irVTzy6nKk2fLzpN2hZ77fy1B7fqUgW97de/cmxKlVTBw3NzwNLhGzy4Qcutis6TwqFz4kTuMjpT/tAfVaxo8ak2aP/E+pSeojCPA5F4jtCcMyB5ZuYZ9JOiJA/xe6OcFS4x9LHx7R0XYr0FwFJF5ovYpHtGqTYQvRAD4jLlcmsGhiFPJK/jm4VGcOJHJ0hzIYnVMjGJ4tWT33C60dOroYMYJo1f+5eGxY96XZFifmsxwme/ogFm9UkvbJbSBUKa4CZySMpDxZBZsWlohkJmAwM2MAmQomVjh3LK6yHxG0RVpafIoPkn8WBZVbAN16tPs8XqQn54D3RQhe9aZvMqvqjbmIBKrB5tPxPcyYFRvAAMfZI3tVU04kVbh4qNNQVd7GsWH++QHqZz6i6CJ7LTUzuRJ4Dg+XJLEYYJemuZ5U+SqgH7N4LL9Kfqm+FsXBEbhSn4dlF6ezH7IRDlJGRpS0+7Tb/7FjlcYMPn4wKLMRvUgU6x1KCtQTQkgcNHjJlrRMcd/uQjNuxi4Q0uqHP2E/Izc=
    -
      # LTD_USERNAME
      secure: SAIGdF4sORc9wT7PlOu7QA5rlyYkkWxYNi/+f5VulcR1lihzTwApZ7wD1kVrMq7qwsEyhp3h9MN2ZtJ2gY3CLxMqzfR2j2IJLbOixb4hXpX1kc2YzqsBfCICwoO3fVfK1Ewn62COmjOFnJGg8mi84lL032FOygXec4lZ0WR0E7xn42QqQe1ksQcHJmnTI42/ZkSYXg6NkhqtSuHj0sPeHBsHAqRHJ6I+nQGLBkRPAb1ehvi6O/xpwJDeRb4tObDvENB9lpfqGdwIw3v1WejPwhNg9siE+LQVwjiiPeJq6aBHSYYRn+U75KxYNDvqGitU6kCqTfCBKLIXEZ8AAp4q7m+OJV/guXtTewobyc7bLAAQ8cAasxrxzA4/nnR/YEqW1q4SAnM6ESdaQahLcw5q2YAouEQuIleypHAD4w54X6RLPpMW/pR6bwuQC+entAR3AKgtEZ0PpFptk35pTh76UQPsVU95ZCcr+RucC57GM2yEv2VTe47Bh+/wiZJeoz1vWZEPxbQGWpVzE1q9v514OmcYTrl8NDRSf4oITF1lG4VEsrr4XoM+VjPDB9I2y2j5ilDtN7s7X+GzJHrdMjn6bQOrX2ShS8+ABf0kQ5fIeDmQCbKVneyTPmYMZ5ma9S4sk00u/SNQ6MhaC1ZWZIZOz2u0Pe6m89XnIgOdsl8ZQL4=
    -
      # LTD_PASSWORD
      secure: kpCAGaC27fxAj31IgHkDOa+z/DCbbdWqzJKRpoZPV6wRblRsGhA0xDb7OJznmCcNPdPQmpq4wUsz+hOWK7UAIrfB3+/CTnqcBWE8Brxtyx/5nmrn6xsndhVruYPVG+0FP+bRiidBWdLpm0NQJDuN5q2kr1/d5Psuk1/OPRUSoIKaXJxaVn8WX3ylMQZ/Ml6UOBS8iq9cUdhXQOXdxSDgxZxxVzIKZHgHMgwlIOcxcQbgW5++fWxFtcs+yACEyp74LWlTvqDABrTBCxcBn1gWN+vMYxdVc4cyoju3IxQBw1+hlaZqlb7Aq4jhv4FZMYu0QONr6WuW/6eUXt6Fcuaq7ao4jFzjAkQ+qAZzYSYojmxIlJ/Yc0p91cFLB3z4JhflpjHrZ3N1buWKfv8UnqR7SddgLIV++hN9ZeJxLVKpIdO49yDA1TbZhvj4sDUJCIyimzTqH6VB1D0Lrp1+aG/mJ9P390WjoHCTTG5KM94XSqkaKa20V1uCXSYgcQditUhfF9IOjdh0Gv9RjDaxTbd8SKEA9YG+jEeT88TGc/xJlxzgh9wVawys+XQoUU9DQGUc7P+prd7nnaHgAw8Bat+zBntD4dg24vApk//IbCgjRNo29fK/PgeYrXizZGU2xYt1HEAER8z2yN51yj2vFJcVzO8gHvv9ifAdL8EzLtz4900=
